platform :ios, '9.0'
use_frameworks!
use_modular_headers!

inhibit_all_warnings!

target 'DKImagePickerControllerDemo' do

 pod 'DKImagePickerController', :path => '../'

  # Pods for DKImagePickerControllerDemo

end
